{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.internal.desktop.monitor-profiles;

  # The watcher script needs an absolute `use` path to the switch module so
  # it works under `nu script.nu` (which does not load config.nu). We
  # substitute the home directory at activation time rather than baking the
  # path into the source file.
  watcherScript = pkgs.writeText "monitor-profiles-watcher.nu" (
    builtins.replaceStrings
      [ "@USER_HOME@" ]
      [ config.home.homeDirectory ]
      (builtins.readFile ./monitor-profiles-watcher.nu)
  );
in
{
  options.internal.desktop.monitor-profiles = {
    enable = mkEnableOption "DDC/CI monitor profile switching";

    displaySerial = mkOption {
      type = types.str;
      description = "DDC display serial, from `ddcutil detect`.";
    };

    vcpFeature = mkOption {
      type = types.str;
      description = "VCP feature code controlling mode (hex, no 0x prefix).";
    };

    srgbValue = mkOption {
      type = types.str;
      description = "Primary VCP value for sRGB mode (e.g. \"0x0f\").";
    };

    hdrValue = mkOption {
      type = types.str;
      description = "Primary VCP value for HDR mode (e.g. \"0x27\").";
    };

    secondary = {
      enable = mkEnableOption "secondary VCP feature write";
      feature = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Secondary VCP feature code (required if secondary.enable).";
      };
      srgbValue = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Secondary VCP sRGB value (required if secondary.enable).";
      };
      hdrValue = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "Secondary VCP HDR value (required if secondary.enable).";
      };
    };

    useSidechannel = mkEnableOption "LG DDC2AB i2c sidechannel for writes";

    triggerApps = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = ''
        Niri app_ids that force sRGB while any is open. Last one closes -> HDR.
        Leave empty to disable auto-switching.
      '';
      example = [ "Blender" "rapidraw" ];
    };

    bar.enable = mkOption {
      type = types.bool;
      default = true;
      description = "Install the DankMaterialShell bar toggle plugin.";
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      assertions = [
        {
          assertion = config.programs.nushell.enable;
          message = "internal.desktop.monitor-profiles requires programs.nushell.enable = true";
        }
        {
          assertion = !cfg.secondary.enable
            || (cfg.secondary.feature != null
                && cfg.secondary.srgbValue != null
                && cfg.secondary.hdrValue != null);
          message = "internal.desktop.monitor-profiles.secondary.enable requires feature, srgbValue, and hdrValue to be non-null";
        }
      ];

      home.packages = [ pkgs.ddcutil ];

      xdg.configFile."nushell/modules/monitor-profile-config.nu".text = ''
        # monitor-profile-config.nu — generated by home-manager, do not edit.
        export const DISPLAY_SERIAL    = "${cfg.displaySerial}"
        export const VCP_FEATURE       = "${cfg.vcpFeature}"
        export const SRGB_VALUE        = "${cfg.srgbValue}"
        export const HDR_VALUE         = "${cfg.hdrValue}"
        export const USE_SIDECHANNEL   = ${if cfg.useSidechannel then "true" else "false"}
        export const SECONDARY_ENABLE  = ${if cfg.secondary.enable then "true" else "false"}
        export const SECONDARY_FEATURE = "${if cfg.secondary.feature == null then "" else cfg.secondary.feature}"
        export const SECONDARY_SRGB    = "${if cfg.secondary.srgbValue == null then "" else cfg.secondary.srgbValue}"
        export const SECONDARY_HDR     = "${if cfg.secondary.hdrValue == null then "" else cfg.secondary.hdrValue}"
      '';

      xdg.configFile."nushell/modules/monitor-profile-switch.nu".source =
        ./monitor-profile-switch.nu;

      programs.nushell.extraConfig = ''
        use ${config.home.homeDirectory}/.config/nushell/modules/monitor-profile-switch.nu *
      '';
    }

    (mkIf cfg.bar.enable {
      # The DMS home-manager module installs the plugin via xdg.configFile
      # AND registers it in ~/.config/DankMaterialShell/plugin_settings.json
      # so DMS actually loads it. Doing the install via xdg.configFile
      # ourselves wasn't enough — DMS needs the settings entry to enable.
      programs.dank-material-shell.plugins.monitorProfileToggle = {
        enable = true;
        src = ./plugin;
      };
    })

    (mkIf (cfg.triggerApps != [ ]) {
      systemd.user.services.monitor-profiles-watcher = {
        Unit = {
          Description = "Monitor profile auto-switcher (Niri event watcher)";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart =
            "${pkgs.nushell}/bin/nu ${watcherScript} "
            + escapeShellArgs cfg.triggerApps;
          Restart = "on-failure";
          RestartSec = "5s";
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
    })
  ]);
}
