# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  parameters: []
  resources:
    #----------------------------------------------------------------------------------------------#
    # Settings & configurations.
    #----------------------------------------------------------------------------------------------#
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable Dark Mode
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Configure Taskbar
        allowPrerelease: true
      settings:
        Alignment: Middle
        SearchboxMode: Hide
        TaskViewButton: Hide
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Configure Explorer
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
        ItemCheckBoxes: Hide
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present

    - resource: Microsoft.PowerToys.Configure/PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        FancyZones:
          Enabled: true
      dependsOn:
        - installPowerToys

    #----------------------------------------------------------------------------------------------#
    # Package managers.
    #----------------------------------------------------------------------------------------------#
    - resource: xScoop/ScoopInstall
      id: installScoop
      directives:
        description: Install Scoop
      settings:
        Ensure: Present

    - resource: xScoop/ScoopBucket
      id: installScoopExtras
      directives:
        description: Install Scoop extras bucket
      settings:
        Name: extras
        Ensure: Present
      dependsOn:
        - installGit
        - install7zip

    - resource: xScoop/ScoopBucket
      id: installScoopNerdFonts
      directives:
        description: Install Scoop nerd-fonts bucket
      settings:
        Name: nerd-fonts
        Ensure: Present
      dependsOn:
        - installGit
        - install7zip

    - resource: xChoco/ChocoInstall
      id: installChoco
      directives:
        description: Install Chocolatey
      settings:
        Ensure: Present

    #----------------------------------------------------------------------------------------------#
    # Drivers.
    #----------------------------------------------------------------------------------------------#
    - resource: xPkg/PkgDownloadAndInstall
      id: installAmdGraphicsDriver
      directives:
        description: Install AMD Graphics Driver
      settings:
        If: Get-WmiObject -Query 'SELECT * FROM Win32_VideoController' | Where-Object {$_.Name -like '*AMD*'}
        Name: AMD Software
        Type: EXE
        Arguments: /S
        Url: https://drivers.amd.com/drivers/installer/24.10/whql/amd-software-adrenalin-edition-24.7.1-minimalsetup-240730_web.exe
        Headers:
          Sec-Fetch-Site: same-site
          Pragma: no-cache
          Sec-Fetch-Mode: navigate
          Sec-Fetch-User: "?1"
          Upgrade-Insecure-Requests: "1"
          Referer: https://www.amd.com/
        Ensure: Present

    - resource: xPkg/PkgDownloadAndInstall
      id: installNvidiaGraphicsDriver
      directives:
        description: Install NVIDIA Graphics Driver
      settings:
        If: Get-WmiObject -Query 'SELECT * FROM Win32_VideoController' | Where-Object {$_.Name -like '*NVIDIA*'}
        Name: NVIDIA GeForce Experience
        Type: EXE
        Arguments: /S
        Url: https://de.download.nvidia.com/GFE/GFEClient/3.27.0.120/GeForce_Experience_v3.27.0.120.exe
        Ensure: Present

    - resource: xPkg/PkgDownloadAndInstall
      id: installFocusriteScarlett2i2Driver
      directives:
        description: Install Focusrite Scarlett 2i2 USB Audio Interface Driver
      settings:
        Name: Focusrite Control 2
        Type: EXE
        Arguments: /silent /NORESTART
        Url: https://releases.focusrite.com/com.focusrite.focusrite-control/latest/Focusrite-Control-2.exe
        Ensure: Present

    #----------------------------------------------------------------------------------------------#
    # Packages.
    #----------------------------------------------------------------------------------------------#
    - resource: xScoop/ScoopApp
      id: install7zip
      directives:
        description: Install 7-Zip
      settings:
        Name: 7zip
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: xScoop/ScoopApp
      id: installGit
      directives:
        description: Install Git
      settings:
        Name: git
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: xScoop/ScoopApp
      id: installMake
      directives:
        description: Install make
      settings:
        Name: make
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installWindowsTerminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        Id: Microsoft.WindowsTerminal
        Source: winget
        Ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installPowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        Id: Microsoft.PowerToys
        Source: winget
        Ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installVisualStudioCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        Id: Microsoft.VisualStudioCode
        Source: winget
        Ensure: Present

    - resource: cChoco/cChocoPackageInstaller
      id: installGoogleDrive
      directives:
        description: Install Google Drive
      settings:
        Name: googledrive
        Ensure: Present
      dependsOn:
        - installChoco

  configurationVersion: "0.2.0"
