# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"
  parameters: []
  resources:
    #----------------------------------------------------------------------------------------------#
    # General settings & configurations.
    #----------------------------------------------------------------------------------------------#
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable Dark Mode
        allowPrerelease: true
      settings:
        Ensure: Present
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Configure Taskbar
        allowPrerelease: true
      settings:
        Alignment: Middle
        SearchboxMode: Hide
        TaskViewButton: Hide
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Configure Explorer
        allowPrerelease: true
      settings:
        FileExtensions: Show
        HiddenFiles: Show
        ItemCheckBoxes: Hide
        RestartExplorer: true

    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    # - resource: Microsoft.PowerToys.Configure/PowerToysConfigure
    #   dependsOn:
    #     - installPowerToys
    #   directives:
    #     description: Configure PowerToys

    #----------------------------------------------------------------------------------------------#
    # Package managers.
    #----------------------------------------------------------------------------------------------#
    - resource: xScoop/ScoopInstall
      id: installScoop
      directives:
        description: Install Scoop
      settings:
        Ensure: Present

    - resource: xScoop/ScoopBucket
      id: installScoopExtras
      directives:
        description: Install Scoop extras bucket
      settings:
        Name: extras
        Ensure: Present
      dependsOn:
        - installGit
        - install7zip

    - resource: xScoop/ScoopBucket
      id: installScoopNerdFonts
      directives:
        description: Install Scoop nerd-fonts bucket
      settings:
        Name: nerd-fonts
        Ensure: Present
      dependsOn:
        - installGit
        - install7zip

    # - resource: cChoco/cChocoInstaller
    #   id: installChoco
    #   directives:
    #     description: Install Chocolatey
    #   settings:
    #     InstallDir: C:\ProgramData\chocolatey

    #----------------------------------------------------------------------------------------------#
    # Packages.
    #----------------------------------------------------------------------------------------------#
    - resource: xScoop/ScoopApp
      id: install7zip
      directives:
        description: Install 7-Zip
      settings:
        Name: 7zip
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: xScoop/ScoopApp
      id: installGit
      directives:
        description: Install Git
      settings:
        Name: git
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: xScoop/ScoopApp
      id: installMake
      directives:
        description: Install make
      settings:
        Name: make
        NoUpdateScoop: true
        Ensure: Present
      dependsOn:
        - installScoop

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installPowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        Id: Microsoft.PowerToys
        Source: winget
        Ensure: Present

  configurationVersion: "0.2.0"
