# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
imports: []

properties:
  configurationVersion: "0.2.0"
  assertions: []
  parameters: []
  resources:
    []
    # - resource: xPSDesiredStateConfiguration/xEnvironment
    #   id: setXDGConfigHomeEnvVar
    #   directives:
    #     description: Set XDG_CONFIG_HOME Environment Variable
    #   settings:
    #     Name: XDG_CONFIG_HOME
    #     Value: "%USERPROFILE%\\.config"
    #     Ensure: Present
