workspaces:
  - name: web
    display_name: Web
    bind_to_monitor: 0
  - name: mail
    display_name: Mail
    bind_to_monitor: 0
  - name: calendar
    display_name: Calendar
    bind_to_monitor: 0
  - name: music
    display_name: Music
    bind_to_monitor: 0
  - name: main
    display_name: Main
    bind_to_monitor: 1
  - name: scratch
    display_name: Scratch
    bind_to_monitor: 1
  - name: notion
    display_name: Notion
    bind_to_monitor: 1
  - name: discord
    display_name: Discord
    bind_to_monitor: 1
  - name: gaming
    display_name: Gaming
    bind_to_monitor: 1
  - name: glance
    display_name: Glance
    bind_to_monitor: 2
  - name: pomodoro
    display_name: Pomodoro
    bind_to_monitor: 2
  - name: comms
    display_name: Comms
    bind_to_monitor: 2
  - name: yt
    display_name: YT
    bind_to_monitor: 2
  - name: chatgpt
    display_name: ChatGPT
    bind_to_monitor: 2
