general:
  startup_commands:
    - "shell-exec zebar"
    - "shell-exec %Userprofile%/.local/bin/winapp.bat spotify"
    - "shell-exec %Userprofile%/.local/bin/winapp.bat chatgpt"
    - "shell-exec %Userprofile%/.local/bin/winapp.bat whatsapp"
    - "shell-exec %Userprofile%/.local/bin/discord.bat"
    - "shell-exec %AppData%/Telegram Desktop/Telegram.exe"
    - "shell-exec %LocalAppData%/proton_mail/Proton Mail.exe"
    - "shell-exec %LocalAppData%/Programs/cron-web/Notion Calendar.exe"
    - "shell-exec %LocalAppData%/Programs/Notion/Notion.exe"
    - "shell-exec %ProgramFiles%/Mozilla Thunderbird/thunderbird.exe"
    - "shell-exec %ProgramFiles%/Zen Browser/zen.exe"
    - "shell-exec %ProgramFiles(x86)%/Microsoft/Edge/Application/msedge.exe --app=https://app.flocus.com"
    - "focus --workspace notion"
  shutdown_commands:
    - "shell-exec taskkill /IM zebar.exe /F"
  config_reload_commands: []

  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: "window_focus"

gaps:
  scale_with_dpi: true
  inner_gap: "10px"
  outer_gap:
    top: "50px"
    bottom: "10x"
    right: "10px"

    left: "10px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#7dc4e4"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"
  other_windows:
    border:
      enabled: true
      color: "#6e738d"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"

window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }
      - window_process: { regex: "Focusrite Control 2" }
      - window_process: { regex: "VoiceMeeter" }
      - window_process: { regex: "LG UltraGear Control Center" }
      - window_class: { equals: "UnitySplashWindow" }
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "Flow.Launcher" }
      - window_title: { equals: "Settings" }
      - window_title: { equals: "Task Manager" }
      - window_process: { equals: "vlc" }

  - commands: ["move --workspace main", focus --workspace main]
    match:
      - window_title: { regex: ".*WezTerm.*" }
      - window_process: { equals: "Code" }
      - window_process: { equals: "Unity" }
      - window_process: { equals: "Rider" }

  - commands: ["move --workspace scratch", focus --workspace scratch]
    match:
      - window_process: { equals: "Unity Hub" }

  - commands: ["move --workspace pomodoro", focus --workspace pomodoro]
    match:
      - window_title: { equals: "Flocus" }

  - commands: ["move --workspace notion", focus --workspace notion]
    match:
      - window_process: { equals: "Notion" }

  - commands: ["move --workspace gaming", focus --workspace gaming]
    match:
      - window_title: { regex: ".*Steam.*" }
      - window_process: { equals: "EpicGamesLauncher" }

  - commands: ["move --workspace web", focus --workspace web]
    match:
      - window_process: { equals: "arc" }
      - window_process: { equals: "zen" }

  - commands: ["move --workspace comms"]
    match:
      - window_process: { equals: "Telegram" }
      - window_title: { equals: "WhatsApp" }

  - commands: ["move --workspace discord"]
    match:
      - window_process: { equals: "Discord" }

  - commands: ["move --workspace mail"]
    match:
      - window_process: { equals: "Proton Mail" }
      - window_title: { regex: ".*Thunderbird.*" }

  - commands: ["move --workspace calendar"]
    match:
      - window_process: { equals: "Notion Calendar" }

  - commands: ["move --workspace music"]
    match:
      - window_process: { equals: "Spotify" }

  - commands: ["move --workspace chatgpt"]
    match:
      - window_process: { equals: "ChatGPT" }

binding_modes:
  - name: "focus"
    display_name: "Focus Mode"
    keybindings:
      - commands: ["focus --direction left"]
        bindings: ["j", "left"]
      - commands: ["focus --direction right"]
        bindings: ["l", "right"]
      - commands: ["focus --direction up"]
        bindings: ["i", "up"]
      - commands: ["focus --direction down"]
        bindings: ["k", "down"]

      - commands: ["focus --next-workspace"]
        bindings: ["o"]
      - commands: ["focus --prev-workspace"]
        bindings: ["u"]

      - commands: ["focus --recent-workspace"]
        bindings: ["r"]

      - commands: ["focus --workspace main"]
        bindings: ["1"]
      - commands: ["focus --workspace web"]
        bindings: ["2"]
      - commands: ["focus --workspace scratch"]
        bindings: ["3"]
      - commands: ["focus --workspace glance"]
        bindings: ["4"]

      - commands: ["wm-disable-binding-mode --name focus"]
        bindings: ["escape", "ctrl+alt+x"]

  - name: "move"
    display_name: "Move Mode"
    keybindings:
      - commands: ["move --direction left"]
        bindings: ["j", "left"]
      - commands: ["move --direction right"]
        bindings: ["l", "right"]
      - commands: ["move --direction up"]
        bindings: ["i", "up"]
      - commands: ["move --direction down"]
        bindings: ["k", "down"]

      - commands: ["move --workspace main", "focus --workspace main"]
        bindings: ["1"]
      - commands: ["move --workspace scratch", "focus --workspace scratch"]
        bindings: ["2"]
      - commands: ["move --workspace glance", "focus --workspace glance"]
        bindings: ["3"]

      - commands: ["move-workspace --direction left"]
        bindings: ["ctrl+j"]
      - commands: ["move-workspace --direction right"]
        bindings: ["ctrl+l"]
      - commands: ["move-workspace --direction up"]
        bindings: ["ctrl+i"]
      - commands: ["move-workspace --direction down"]
        bindings: ["ctrl+k"]

      - commands: ["wm-disable-binding-mode --name move"]
        bindings: ["escape", "ctrl+shift+x"]

  - name: "resize"
    display_name: "Resize Mode"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["s", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["f", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["e", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["d", "down"]

      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "ctrl+alt+shift+x"]

  - name: "pause"
    display_name: "Pause Mode"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  # ------------------------------------ #
  # Launching apps.
  # ------------------------------------ #

  - commands: ["shell-exec wezterm-gui"]
    bindings: ["ctrl+shift+enter"]

  # ------------------------------------ #
  # Focusing (leader = ctrl+alt).
  # ------------------------------------ #

  # Enable focus mode.
  - commands: ["wm-enable-binding-mode --name focus"]
    bindings: ["ctrl+alt+x"]

  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["ctrl+alt+j"]
  - commands: ["focus --direction right"]
    bindings: ["ctrl+alt+l"]
  - commands: ["focus --direction up"]
    bindings: ["ctrl+alt+i"]
  - commands: ["focus --direction down"]
    bindings: ["ctrl+alt+k"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["ctrl+alt+o"]
  - commands: ["focus --prev-workspace"]
    bindings: ["ctrl+alt+u"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["ctrl+alt+."]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace main"]
    bindings: ["ctrl+alt+1"]
  - commands: ["focus --workspace web"]
    bindings: ["ctrl+alt+2"]
  - commands: ["focus --workspace scratch"]
    bindings: ["ctrl+alt+3"]
  - commands: ["focus --workspace glance"]
    bindings: ["ctrl+alt+4"]

  # ------------------------------------ #
  # Movement (leader = ctrl+shift).
  # ------------------------------------ #

  # Enable move mode.
  - commands: ["wm-enable-binding-mode --name move"]
    bindings: ["ctrl+shift+x"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["ctrl+shift+j"]
  - commands: ["move --direction right"]
    bindings: ["ctrl+shift+l"]
  - commands: ["move --direction up"]
    bindings: ["ctrl+shift+i"]
  - commands: ["move --direction down"]
    bindings: ["ctrl+shift+k"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace main", "focus --workspace main"]
    bindings: ["ctrl+shift+1"]
  - commands: ["move --workspace scratch", "focus --workspace scratch"]
    bindings: ["ctrl+shift+2"]
  - commands: ["move --workspace glance", "focus --workspace glance"]
    bindings: ["ctrl+shift+3"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["ctrl+alt+shift+j"]
  - commands: ["move-workspace --direction right"]
    bindings: ["ctrl+alt+shift+l"]
  - commands: ["move-workspace --direction up"]
    bindings: ["ctrl+alt+shift+i"]
  - commands: ["move-workspace --direction down"]
    bindings: ["ctrl+alt+shift+k"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["ctrl+shift+q"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["ctrl+shift+w"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["ctrl+shift+r"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["ctrl+shift+t"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["ctrl+shift+v"]

  # ------------------------------------ #
  # Resizing (leader = ctrl+alt+shift).
  # ------------------------------------ #

  # Enable resize modek.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["ctrl+alt+shift+x"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width +2%"]
    bindings: ["ctrl+alt+shift+f"]
  - commands: ["resize --width -2%"]
    bindings: ["ctrl+alt+shift+s"]
  - commands: ["resize --height +2%"]
    bindings: ["ctrl+alt+shift+d"]
  - commands: ["resize --height -2%"]
    bindings: ["ctrl+alt+shift+e"]

  # ------------------------------------ #
  # Misc.
  # ------------------------------------ #

  # Enable pause mode.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]
