general:
  startup_commands:
    - "shell-exec zebar"
    - "shell-exec %ProgramFiles%/Unity Hub/Unity Hub.exe"
    - "shell-exec %LocalAppData%/Fork/Fork.exe"
    - "shell-exec %LocalAppData%/AnthropicClaude/claude.exe"
    - "shell-exec %Userprofile%/.local/bin/chatgpt.bat"
    - "shell-exec %LocalAppData%/Programs/Notion/Notion.exe"
    - "shell-exec %LocalAppData%/Programs/cron-web/Notion Calendar.exe"
    - "shell-exec %Userprofile%/.local/bin/discord.bat"
    - "shell-exec %AppData%/Telegram Desktop/Telegram.exe"
    - "shell-exec %Userprofile%/.local/bin/whatsapp.bat"
    - "shell-exec %LocalAppData%/proton_mail/Proton Mail.exe"
    - "shell-exec %ProgramFiles%/Mozilla Thunderbird/thunderbird.exe"
    - "shell-exec %AppData%/Spotify/Spotify.exe"
    - "shell-exec %ProgramFiles%/Zen Browser/zen.exe"
  shutdown_commands:
  
    - "shell-exec taskkill /IM zebar.exe /F"
  config_reload_commands: []

  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: "window_focus"

gaps:
  scale_with_dpi: true
  inner_gap: "10px"
  outer_gap:
    top: "50px"
    bottom: "10x"
    right: "10px"
    left: "10px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#7dc4e4"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"
  other_windows:
    border:
      enabled: true
      color: "#6e738d"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "rounded"

window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

workspaces:
  # Left portrait  monitor.
  - name: git
    display_name: Git
    bind_to_monitor: 0
  - name: unity
    display_name: Unity
    bind_to_monitor: 0

  # Central widescreen monitor.
  - name: main
    display_name: Main
    bind_to_monitor: 1
  - name: gaming
    display_name: Gaming
    bind_to_monitor: 1
  - name: scratch
    display_name: Scratch
    bind_to_monitor: 1

  # Below central widescreen monitor.
  - name: web
    display_name: Web
    bind_to_monitor: 2
  - name: discord
    display_name: Discord
    bind_to_monitor: 2
  - name: comms
    display_name: Comms
    bind_to_monitor: 2
  - name: mail
    display_name: Mail
    bind_to_monitor: 2
  - name: calendar
    display_name: Calendar
    bind_to_monitor: 2
  - name: music
    display_name: Music
    bind_to_monitor: 2

  # Right portrait monitor.
  - name: chatgpt
    display_name: ChatGPT
    bind_to_monitor: 3
  - name: claude
    display_name: Claude
    bind_to_monitor: 3

window_rules:
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }
      - window_process: { regex: "Focusrite Control 2" }
      - window_process: { regex: "VoiceMeeter" }
      - window_process: { regex: "LG UltraGear Control Center" }
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "Flow.Launcher" }
      - window_title: { equals: "Settings" }
      - window_title: { equals: "Task Manager" }

  - commands: ["move --workspace main", focus --workspace main]
    match:
      - window_title: { regex: ".*WezTerm.*" }
      - window_process: { equals: "Notion" }
      - window_process: { equals: "Code" }
      - window_process: { equals: "Unity" }
      - window_process: { equals: "Rider" }

  - commands: ["move --workspace gaming", focus --workspace gaming]
    match:
      - window_title: { regex: ".*Steam.*" }
      - window_process: { equals: "EpicGamesLauncher" }

  - commands: ["move --workspace web", focus --workspace web]
    match:
      - window_process: { equals: "arc" }
      - window_process: { equals: "zen" }

  - commands: ["move --workspace comms"]
    match:
      - window_process: { equals: "Telegram" }
      - window_title: { equals: "WhatsApp" }

  - commands: ["move --workspace discord"]
    match:
      - window_process: { equals: "Discord" }

  - commands: ["move --workspace mail"]
    match:
      - window_process: { equals: "Proton Mail" }
      - window_title: { regex: ".*Thunderbird.*" }

  - commands: ["move --workspace calendar"]
    match:
      - window_process: { equals: "Notion Calendar" }

  - commands: ["move --workspace git"]
    match:
      - window_process: { equals: "Fork" }

  - commands: ["move --workspace unity"]
    match:
      - window_process: { equals: "Unity Hub" }

  - commands: ["move --workspace music"]
    match:
      - window_process: { equals: "Spotify" }

  - commands: ["move --workspace chatgpt"]
    match:
      - window_process: { equals: "ChatGPT" }

  - commands: ["move --workspace claude"]
    match:
      - window_process: { equals: "claude" }

binding_modes:
  - name: "focus"
    display_name: "Focus Mode"
    keybindings:
      - commands: ["focus --direction left"]
        bindings: ["j", "left"]
      - commands: ["focus --direction right"]
        bindings: ["l", "right"]
      - commands: ["focus --direction up"]
        bindings: ["i", "up"]
      - commands: ["focus --direction down"]
        bindings: ["k", "down"]

      - commands: ["focus --next-workspace"]
        bindings: ["o"]
      - commands: ["focus --prev-workspace"]
        bindings: ["u"]

      - commands: ["focus --workspace main"]
        bindings: ["1", "a"]
      - commands: ["focus --workspace web"]
        bindings: ["2", "s"]
      - commands: ["focus --workspace scratch"]
        bindings: ["3", "d"]

      - commands: ["wm-disable-binding-mode --name focus"]
        bindings: ["escape", "ctrl+d"]

  - name: "resize"
    display_name: "Resize Mode"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["j", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["i", "down"]

      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "ctrl+alt+d"]

  - name: "move"
    display_name: "Move Mode"
    keybindings:
      - commands: ["move --direction left"]
        bindings: ["j", "left"]
      - commands: ["move --direction right"]
        bindings: ["l", "right"]
      - commands: ["move --direction up"]
        bindings: ["i", "up"]
      - commands: ["move --direction down"]
        bindings: ["k", "down"]

      - commands: ["move --workspace main", "focus --workspace main"]
        bindings: ["1", "a"]
      - commands: ["move --workspace web", "focus --workspace web"]
        bindings: ["2", "s"]
      - commands: ["move --workspace scratch", "focus --workspace scratch"]
        bindings: ["3", "d"]

      - commands: ["move-workspace --direction left"]
        bindings: ["ctrl+j"]
      - commands: ["move-workspace --direction right"]
        bindings: ["ctrl+l"]
      - commands: ["move-workspace --direction up"]
        bindings: ["ctrl+i"]
      - commands: ["move-workspace --direction down"]
        bindings: ["ctrl+k"]

      - commands: ["wm-disable-binding-mode --name move"]
        bindings: ["escape", "ctrl+shift+d"]

  - name: "pause"
    display_name: "Pause Mode"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]

keybindings:
  # Focusing (leader = ctrl).

  # Enable focus mode.
  - commands: ["wm-enable-binding-mode --name focus"]
    bindings: ["ctrl+d"]

  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["ctrl+j"]
  - commands: ["focus --direction right"]
    bindings: ["ctrl+l"]
  - commands: ["focus --direction up"]
    bindings: ["ctrl+i"]
  - commands: ["focus --direction down"]
    bindings: ["ctrl+k"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["ctrl+o"]
  - commands: ["focus --prev-workspace"]
    bindings: ["ctrl+u"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["ctrl+r"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace main"]
    bindings: ["ctrl+1"]
  - commands: ["focus --workspace web"]
    bindings: ["ctrl+2"]
  - commands: ["focus --workspace scatch"]
    bindings: ["ctrl+3"]

  # Movement (leader = ctrl+shift).

  # Enable move mode.
  - commands: ["wm-enable-binding-mode --name move"]
    bindings: ["ctrl+shift+d"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["ctrl+shift+j"]
  - commands: ["move --direction right"]
    bindings: ["ctrl+shift+l"]
  - commands: ["move --direction up"]
    bindings: ["ctrl+shift+i"]
  - commands: ["move --direction down"]
    bindings: ["ctrl+shift+k"]

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["ctrl+shift+alt+j"]
  - commands: ["move-workspace --direction right"]
    bindings: ["ctrl+shift+alt+l"]
  - commands: ["move-workspace --direction up"]
    bindings: ["ctrl+shift+alt+i"]
  - commands: ["move-workspace --direction down"]
    bindings: ["ctrl+shift+alt+k"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace main", "focus --workspace main"]
    bindings: ["ctrl+shift+1"]
  - commands: ["move --workspace web", "focus --workspace web"]
    bindings: ["ctrl+shift+2"]
  - commands: ["move --workspace scratch", "focus --workspace scratch"]
    bindings: ["ctrl+shift+3"]

  # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["ctrl+shift+x"]

  # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["ctrl+shift+f"]

  # Close focused window.
  - commands: ["close"]
    bindings: ["ctrl+shift+c"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["ctrl+shift+v"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["ctrl+shift+space"]

  # Not sure what this does.
  # Change focus from tiling windows -> floating -> fullscreen.
  # - commands: ["wm-cycle-focus"]
  #   bindings: ["alt+space"]

  # Resizing (leader = ctrl+alt).

  # Enable resize modek.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["ctrl+alt+d"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["ctrl+alt+j"]
  - commands: ["resize --width +2%"]
    bindings: ["ctrl+alt+l"]
  - commands: ["resize --height +2%"]
    bindings: ["ctrl+alt+k"]
  - commands: ["resize --height -2%"]
    bindings: ["ctrl+alt+i"]

  # Launching apps.
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["ctrl+shift+enter"]

  # Misc.

  # Enable pause mode.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]
